
import argparse
from html import escape
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[4]
CONFIG = Path(__file__).with_name("about.toml")
REPORT = "THIRD-PARTY-LICENSES.html"
TOOL_VERSION = "cargo-about 0.9.2"
BASE_LICENSES = {"LICENSE": "LICENSE", "assets/icons/LICENSES": "ICON-LICENSES"}
LEGAL_NAME = re.compile(
    r"(?:^|[._-])(licen[cs]es?|copying|copyright|notices?|authors|ofl)(?:$|[._-])", re.I,
)


def gather(target):
    install = "Install cargo-about first: cargo install cargo-about --version 0.9.2 --locked --features cli"
    version = subprocess.run(["cargo", "about", "--version"], cwd=ROOT,
                             capture_output=True, text=True, encoding="utf-8")
    if version.returncode or version.stdout.strip() != TOOL_VERSION:
        raise ValueError(install)
    with tempfile.TemporaryDirectory(prefix="subroutine-licenses-") as directory:
        output = Path(directory) / "licenses.json"
        subprocess.run([
            "cargo", "about", "generate", "--offline", "--locked", "--fail",
            "--manifest-path", str(ROOT / "crates/desktop/Cargo.toml"),
            "--target", target, "--config", str(CONFIG), "--format", "json",
            "--output-file", str(output),
        ], cwd=ROOT, check=True)
        report = json.loads(output.read_text(encoding="utf-8"))
    if not report["crates"] or not report["licenses"]:
        raise ValueError("cargo-about produced no dependency licenses")
    covered = set()
    for license in report["licenses"]:
        if not license["text"].strip() or not license["used_by"]:
            raise ValueError("cargo-about produced an empty license")
        covered.update(user["crate"]["id"] for user in license["used_by"])
    for crate in report["crates"]:
        if (not crate["license"] or crate["license"] in ("Unknown", "Ignore")
                or crate["package"]["id"] not in covered):
            raise ValueError(f"unresolved license for {crate['package']['name']}")
    return report


def package_label(package):
    return f"{package['name']} {package['version']}"


def source_roots(crates):
    roots = {}
    for crate in crates:
        package = crate["package"]
        directory = Path(package["manifest_path"]).resolve().parent
        if directory.is_relative_to(ROOT):
            continue
        source = package.get("source") or ""
        if not source:
            # Local workspace members can symlink licenses shared by the workspace.
            result = subprocess.run([
                "cargo", "metadata", "--offline", "--locked", "--no-deps",
                "--format-version", "1", "--manifest-path", str(directory / "Cargo.toml"),
            ], cwd=ROOT, capture_output=True, text=True, encoding="utf-8", check=True)
            directory = Path(json.loads(result.stdout)["workspace_root"]).resolve()
        elif source.startswith("git+"):
            directory = next((parent for parent in (directory, *directory.parents)
                              if (parent / ".git").exists()), directory)
        roots.setdefault(directory, []).append(package_label(package))
    return roots


def source_documents(root):
    if not root.is_dir():
        raise ValueError(f"dependency source is unavailable: {root}")

    def fail(error):
        raise error

    for directory, children, files in os.walk(root, onerror=fail):
        children[:] = sorted(name for name in children
                             if not name.startswith(".") and name not in ("target", "node_modules"))
        relative = Path(directory).relative_to(root)
        in_licenses = any(part.lower() in ("licenses", "licences") for part in relative.parts)
        for name in sorted(files):
            if in_licenses or LEGAL_NAME.search(name):
                path = Path(directory) / name
                if not path.resolve().is_relative_to(root):
                    raise ValueError(f"license file escapes dependency source: {path}")
                yield relative / name, path.read_text(encoding="utf-8")


def render(report, target):
    parts = [
        '<!doctype html><html lang="en"><head><meta charset="utf-8">',
        '<title>Subroutine Lite — dependency licenses</title>',
        '<style>body{max-width:72rem;margin:2rem auto;padding:0 1rem;font-family:sans-serif}'
        'pre{white-space:pre-wrap;overflow-wrap:anywhere}section{margin:2rem 0}</style>',
        '</head><body><h1>Subroutine Lite — dependency licenses</h1>',
        f'<p>Generated by {TOOL_VERSION} for {escape(target)} from the locked desktop '
        'dependency graph, including build dependencies and excluding dev-only dependencies.</p>',
        '<p>Original source notices are preserved below in addition to resolved license texts. '
        'A canonical-text fallback is identified where the scanner could not extract a license. '
        'This report does not replace source-distribution obligations or a release license review.</p>',
        '<h2>Packages</h2><ul>',
    ]
    for crate in report["crates"]:
        parts.append(f'<li>{escape(package_label(crate["package"]))} — '
                     f'{escape(crate["license"])}</li>')
    parts.append('</ul><h2>Resolved license texts</h2>')
    seen = set()
    for license in report["licenses"]:
        users = ", ".join(package_label(user["crate"]) for user in license["used_by"])
        parts.append(f'<section><h3>{escape(license["name"])}</h3><p>{escape(users)}</p>')
        if not license.get("source_path"):
            parts.append('<p>Canonical license text; check original source notices below.</p>')
        parts.append(f'<pre>{escape(license["text"])}</pre></section>')
        seen.add(license["text"].strip())

    parts.append('<h2>Original source notices</h2>')
    for root, packages in source_roots(report["crates"]).items():
        for relative, text in source_documents(root):
            if not text.strip() or text.strip() in seen:
                continue
            seen.add(text.strip())
            parts.append(f'<section><h3>{escape(str(relative))}</h3>'
                         f'<p>{escape(", ".join(packages))}</p>'
                         f'<pre>{escape(text)}</pre></section>')
    parts.append('</body></html>')
    return "\n".join(parts)


def write_licenses(destination, target, release):
    try:
        generated = render(gather(target), target) if release else None
        destination.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(prefix=".licenses-", dir=destination) as directory:
            staging = Path(directory)
            for source, name in BASE_LICENSES.items():
                shutil.copyfile(ROOT / source, staging / name)
            if generated is not None:
                (staging / REPORT).write_text(generated, encoding="utf-8")
            for path in staging.iterdir():
                path.replace(destination / path.name)
        if generated is None:
            (destination / REPORT).unlink(missing_ok=True)
    except (OSError, ValueError, KeyError, TypeError, subprocess.CalledProcessError) as error:
        raise SystemExit(f"Could not bundle licenses: {error}") from error


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Bundle base licenses and generate dependency licensing for distributable builds."
    )
    parser.add_argument("destination", type=Path)
    parser.add_argument("--target", required=True)
    parser.add_argument("--release", action="store_true")
    args = parser.parse_args()
    write_licenses(args.destination, args.target, args.release)
